[package]
name = "rssfilter"
version = "0.1.0"
edition = "2021"

[dependencies]
filter-rss-feed = { path = "../filter-rss-feed" }
structopt = "=0.3.26"
log = "=0.4.27"
env_logger = "=0.11.7"
regex = "=1.11.1"

[dependencies.tokio]
version = "=1.44.1"
features = ["full"]
