[package]
name = "rssfilter"
version = "0.1.0"
edition = "2021"

[dependencies]
filter-rss-feed = { path = "../filter-rss-feed" }
structopt = "=0.3.26"
log = "=0.4.22"
env_logger = "=0.11.6"
regex = "=1.11.1"

[dependencies.tokio]
version = "=1.43.0"
features = ["full"]
