[package]
name = "lambda-rssfilter"
version = "0.1.0"
edition = "2021"

[dependencies]
aws_lambda_events = "0.15.1"
filter-rss-feed = { path = "../filter-rss-feed" }
http = "1.1.0"
lambda_runtime = "0.12.0"
log = "0.4.21"
once_cell = "1.19.0"
regex = "1.10.5"
reqwest = { version = "0.12.5", features = [
    "json",
    "gzip",
    "brotli",
    "zstd",
    "deflate",
] }
snafu = "0.8.3"
tokio = "1.38.0"
urlencoding = "2.1.3"

[dev-dependencies]
mockito = "1.4.0"
tokio = "1.38.0"
test-utils = { path = "../test-utils", features = ["test-utils"] }
test-case = "3.3.1"
matches = "0.1.10"
