[package]
name = "lambda-rssfilter"
version = "0.1.0"
edition = "2021"

[dependencies]
aws_lambda_events = "0.15.1"
filter-rss-feed = { path = "../filter-rss-feed" }
http = "1.1.0"
lambda-extension = "0.11.0"
lambda_runtime = "0.12.0"
log = "0.4.21"
once_cell = "1.19.0"
opentelemetry = "0.23.0"
opentelemetry-aws = { git = "https://github.com/open-telemetry/opentelemetry-rust-contrib.git", rev = "b62a0ff750d0890a7f75e61629d4f4d153ce1dee" }
opentelemetry-otlp = { version = "0.16.0" }
opentelemetry-semantic-conventions = "0.15.0"
opentelemetry-stdout = "0.4.0"
opentelemetry_sdk = { version = "0.23.0", features = ["rt-tokio"] }
pin-project = "1.1.5"
regex = "1.10.5"
reqwest = { version = "0.12.5", features = [
    "json",
    "gzip",
    "brotli",
    "zstd",
    "deflate",
] }
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["signal"] }
tower = "0.4.13"
tracing = "0.1.40"
tracing-opentelemetry = "0.24.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }
urlencoding = "2.1.3"

[dev-dependencies]
mockito = "1.4.0"
tokio = "1.38.0"
test-utils = { path = "../test-utils", features = ["test-utils"] }
test-case = "3.3.1"
matches = "0.1.10"
