[package]
name = "test-utils"
edition = "2021"

[dependencies]
http = "1.3.1"
rss = "=2.0.12"
urlencoding = "2.1.3"
worker = { version = "0.5.0", features = ["http"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
mockito = "=1.7.0"
