FROM ghcr.io/iainlane/dotfiles-rust-tools:git-24a7c0cfa3e9b909f954a85dd0b4163f6009f02d@sha256:8409474119d2b76e4064b049decdf4764dd2a280cfbcb77d289d65b878a9798c AS rust-tools

FROM public.ecr.aws/aws-cli/aws-cli:2.23.2@sha256:6beaf1e25beacb735467d94b1a3c48446223c5f2cc48682bbf733a3097ec94d2 AS aws-cli

FROM pulumi/pulumi-base:3.146.0@sha256:065f20776fb5259ade4f7bb1d927a916073b356f6bf6139f6367ec623ea5226c AS pulumi

FROM mcr.microsoft.com/devcontainers/rust:1.0.20-1@sha256:9cb8741d565cb7190dbf61aad79d11644cc34e7b1fec34d261c66fff3c9e39ea

COPY --from=aws-cli /usr/local/aws-cli /usr/local/aws-cli
RUN ln -s /usr/local/aws-cli/v2/current/bin/aws /usr/local/bin/aws

COPY --from=rust-tools /usr/local/bin/* /usr/local/bin/

COPY --from=pulumi /pulumi/bin/* /usr/bin/

RUN usermod --login rust --move-home --home /home/rust vscode && \
    groupmod --new-name rust vscode && \
    mv /etc/sudoers.d/vscode /etc/sudoers.d/rust && \
    sed -i 's/vscode/rust/g' /etc/sudoers.d/rust

USER rust
