FROM ghcr.io/iainlane/dotfiles-rust-tools:git-24a7c0cfa3e9b909f954a85dd0b4163f6009f02d@sha256:8409474119d2b76e4064b049decdf4764dd2a280cfbcb77d289d65b878a9798c AS rust-tools

FROM public.ecr.aws/aws-cli/aws-cli:2.19.0@sha256:256d6b71838443a69ccc4b10ba322964ebb8f6af9dabdb3d8a7a1f690aef14f2 AS aws-cli

FROM pulumi/pulumi-base:3.137.0@sha256:f39a31d5bb4bd0efa3bde1bfe988b61a401a51ee59629e5df89a83acf3326bac AS pulumi

FROM mcr.microsoft.com/devcontainers/rust:1.0.18-1@sha256:9904ba28a21257c43294ce9b8a74ca7f9b89189a0d53af73f5ec003bbc351a54

COPY --from=aws-cli /usr/local/aws-cli /usr/local/aws-cli
RUN ln -s /usr/local/aws-cli/v2/current/bin/aws /usr/local/bin/aws

COPY --from=rust-tools /usr/local/bin/* /usr/local/bin/

COPY --from=pulumi /pulumi/bin/* /usr/bin/

RUN usermod --login rust --move-home --home /home/rust vscode && \
    groupmod --new-name rust vscode && \
    mv /etc/sudoers.d/vscode /etc/sudoers.d/rust && \
    sed -i 's/vscode/rust/g' /etc/sudoers.d/rust

USER rust
