FROM ghcr.io/iainlane/dotfiles-rust-tools:git-24a7c0cfa3e9b909f954a85dd0b4163f6009f02d@sha256:8409474119d2b76e4064b049decdf4764dd2a280cfbcb77d289d65b878a9798c AS rust-tools

FROM public.ecr.aws/aws-cli/aws-cli:2.34.37@sha256:bcc201d94b1572ae817c8d7b2ff311904ee09d489179a4e3cc02149429f4346e AS aws-cli

FROM pulumi/pulumi-base:3.232.0@sha256:6afadb67df48f2d01348991f5b9a3466f118c30d9e0dfbb16fac5c0e958f4805 AS pulumi

FROM mcr.microsoft.com/devcontainers/rust:2.0.10-1@sha256:354a0f58f13d93fb6f24e694124fd2d24e6e5306102c7bb3bb1cb26fa4951d46

COPY --from=aws-cli /usr/local/aws-cli /usr/local/aws-cli
RUN ln -s /usr/local/aws-cli/v2/current/bin/aws /usr/local/bin/aws

COPY --from=rust-tools /usr/local/bin/* /usr/local/bin/

COPY --from=pulumi /pulumi/bin/* /usr/bin/

RUN usermod --login rust --move-home --home /home/rust vscode && \
    groupmod --new-name rust vscode && \
    mv /etc/sudoers.d/vscode /etc/sudoers.d/rust && \
    sed -i 's/vscode/rust/g' /etc/sudoers.d/rust

USER rust
