[package]
name = "rssfilter-cli"
edition = "2021"

[[bin]]
name = "rssfilter"
path = "src/main.rs"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "=0.11.8"
filter-rss-feed = { path = "../filter-rss-feed" }
log = "=0.4.27"
regex = "=1.11.2"
structopt = "=0.3.26"
tokio = { version = "=1.47.1", features = ["full"] }
