[package]
name = "filter-rss-feed"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
test-utils = { path = "../test-utils", features = ["test-utils"] }
mockito = "=1.7.0"
tokio = { version = "=1.44.0", features = ["full"] }
test-case = "=3.3.1"

[dependencies]
reqwest = { version = "=0.12.12", features = [
    "json",
    "gzip",
    "brotli",
    "zstd",
    "deflate",
] }
rss = "=2.0.12"
regex = "=1.11.1"
log = "=0.4.26"
env_logger = "=0.11.7"
tracing = "=0.1.41"
thiserror = "=2.0.12"
