[package]
name = "filter-rss-feed"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
test-utils = { path = "../test-utils", features = ["test-utils"] }
mockito = "1.4.0"
tokio = { version = "1", features = ["full"] }
test-case = "3.3.1"

[dependencies]
reqwest = { version = "0.12.5", features = [
    "json",
    "gzip",
    "brotli",
    "zstd",
    "deflate",
] }
rss = "2.0"
regex = "1.5"
log = "0.4"
env_logger = "0.11.3"
tracing = "0.1.40"
thiserror = "1.0.61"
