[package]
name = "filter-rss-feed"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
test-utils = { path = "../test-utils", features = ["test-utils"] }
mockito = "=1.7.0"
tokio = { version = "=1.45.1", features = ["full"] }
test-case = "=3.3.1"

[dependencies]
reqwest = { version = "=0.12.17",default-features = false, features = [
    "http2",
    "json",
    "gzip",
    "brotli",
    "zstd",
    "deflate",
    "rustls-tls",
    "rustls-tls-native-roots",
] }
rss = "=2.0.12"
regex = "=1.11.1"
log = "=0.4.27"
env_logger = "=0.11.8"
tracing = "=0.1.41"
thiserror = "=2.0.12"
