name: "Audit Rust Dependencies"

on:
  push:
    paths:
      # Run if workflow changes
      - ".github/workflows/audit.yml"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "**/audit.toml"
  schedule:
    - cron: "13 4 * * *"

  workflow_dispatch:

permissions: {}

jobs:
  audit:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write

    steps:
      - name: Check out
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: actions-rust-lang/audit@72c09e02f132669d52284a3323acdb503cfc1a24 # v1.2.7
        name: Audit Rust Dependencies
