name: "Test Suite"
on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    strategy:
      matrix:
        config:
          - target: x86_64-unknown-linux-gnu
            sysroot: /usr/lib/x86_64-linux-gnu
          - target: aarch64-unknown-linux-gnu
            sysroot: /usr/lib/aarch64-linux-gnu

    # Share build results via cache between the `build-rust.yml` and `oidc.yml`
    # workflows, because they have the same concurrency group.
    #
    # For pull requests, the concurrency group is based on the pull request's
    # SHA. For pushes, the concurrency group is based on the branch name. This
    # allows the workflows to run concurrently for different branches, but not
    # for the same branch. When we run for pushes, we actually deploy the
    # infrastructure, so we don't want jobs to run concurrently.
    concurrency:
      group: >-
        build-${{
          github.event_name == 'pull_request' &&
          github.sha ||
        github.ref }}-${{ matrix.config.target }}
      cancel-in-progress: false

    name: Build, test, format
    runs-on: ubuntu-24.04

    steps:
      - name: Check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Build
        uses: ./.github/actions/build
        with:
          always-restore-build-cache: true
          build-type:
            ${{ github.event_name == 'pull_request' && 'debug' || 'release' }}
          pkg-config-sysroot: ${{ matrix.config.sysroot }}
          target: ${{ matrix.config.target }}

      - name: Run tests
        if: matrix.config.target == 'x86_64-unknown-linux-gnu'
        run: cargo test --all-features

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@2d1d4e9f72379428552fa1def0b898733fb8472d # v1.1.0
