name: "Test Suite"
on:
  push:
    branches:
      - main

  pull_request:

concurrency:
  # Make sure each push gets a separate concurrency group so pushes to main
  # don't cancel each other.
  group: >-
    build-${{
      github.event_name == 'pull_request' &&
      github.ref ||
      github.sha
    }}
  cancel-in-progress: true

jobs:
  # Actions only allows one waiter per concurrency group, so we do the waiting
  # ourselves.
  turnstile:
    name: Wait for any other builds of ${{ github.workflow }}
    runs-on: ubuntu-24.04

    if: github.event_name == 'push'

    steps:
      - name: Wait
        uses: softprops/turnstyle@49108bdfa571e62371bd2c3094893c547ab3fc03 # v2.2.1
        with:
          continue-after-seconds: 600

  build:
    strategy:
      matrix:
        config:
          - target: x86_64-unknown-linux-gnu
            sysroot: /usr/lib/x86_64-linux-gnu
          - target: aarch64-unknown-linux-gnu
            sysroot: /usr/lib/aarch64-linux-gnu

    # Share build results via cache between the `build-rust.yml` and
    # `pulumi.yml` workflows, because they have the same concurrency group. The
    # later one will wait for the earlier.
    concurrency:
      group: build-${{ github.sha }}-${{ matrix.config.target }}
      cancel-in-progress: false

    name: Build, test, format
    runs-on: ubuntu-24.04

    steps:
      - name: Check out
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Build
        uses: ./.github/actions/build
        with:
          always-restore-build-cache: true
          build-type:
            ${{ github.event_name == 'pull_request' && 'debug' || 'release' }}
          pkg-config-sysroot: ${{ matrix.config.sysroot }}
          target: ${{ matrix.config.target }}

      - name: Run tests
        if: matrix.config.target == 'x86_64-unknown-linux-gnu'
        run: cargo test --all-features

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@2d1d4e9f72379428552fa1def0b898733fb8472d # v1.1.0
