name: Test Suite
on:
  push:
    branches:
      - main

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions: {}

jobs:
  build:
    strategy:
      matrix:
        config:
          - name: x86_64-linux
            flake-system: x86_64-linux
            runs-on: ubuntu-24.04
            check-targets: |
              .#checks.x86_64-linux.build
              .#checks.x86_64-linux.tests
              .#checks.x86_64-linux.clippy
              .#checks.x86_64-linux.doc
              .#checks.x86_64-linux.treefmt
              .#checks.x86_64-linux.statix
              .#checks.x86_64-linux.markdownlint
          - name: aarch64-linux
            flake-system: aarch64-linux
            runs-on: ubuntu-24.04-arm
            check-targets: |
              .#checks.aarch64-linux.build
              .#checks.aarch64-linux.tests
              .#checks.aarch64-linux.clippy
              .#checks.aarch64-linux.doc
          - name: wasm
            flake-system: aarch64-linux
            runs-on: ubuntu-24.04-arm
            check-targets: |
              .#checks.aarch64-linux.build-wasm
              .#checks.aarch64-linux.tests-wasm

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.runs-on }}

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check out
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
        with:
          determinate: false

      - name: Set up Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13
        with:
          use-flakehub: disabled
          use-gha-cache: enabled

      - name: Run checks
        env:
          CHECK_TARGETS: ${{ matrix.config.check-targets }}
        run: |
          mapfile -t nix_checks <<< "${CHECK_TARGETS}"
          nix build -L --keep-going "${nix_checks[@]}"
