name: "Test Suite"
on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    strategy:
      matrix:
        config:
          - target: x86_64-unknown-linux-gnu
            sysroot: /usr/lib/x86_64-linux-gnu
          - target: aarch64-unknown-linux-gnu
            sysroot: /usr/lib/aarch64-linux-gnu

    name: Build
    runs-on: ubuntu-24.04

    steps:
      - name: Check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Build
        uses: ./.github/actions/build
        with:
          pkg-config-sysroot: ${{ matrix.config.sysroot }}
          target: ${{ matrix.config.target }}

  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set Rust toolchain up
        uses: actions-rust-lang/setup-rust-toolchain@1fbea72663f6d4c03efaab13560c8a24cfd2a7cc # v1.9.0

      - name: Run tests
        run: cargo test --all-features

  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set Rust toolchain up
        uses: actions-rust-lang/setup-rust-toolchain@1fbea72663f6d4c03efaab13560c8a24cfd2a7cc # v1.9.0
        with:
          components: rustfmt

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@2d1d4e9f72379428552fa1def0b898733fb8472d # v1.1.0
