on:
  pull_request:

  push:
    branches:
      - main

name: Authenticate with AWS

jobs:
  oidc_debug_test:
    name: Debug OIDC claims

    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout actions-oidc-debugger
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          repository: github/actions-oidc-debugger
          ref: main
          path: ./.github/actions/actions-oidc-debugger

      - name: Debug OIDC Claims
        uses: ./.github/actions/actions-oidc-debugger
        with:
          audience: "${{ github.server_url }}/${{ github.repository_owner }}"

  pulumi:
    # Share build results via cache
    concurrency:
      group:
        build-${{ github.event_name }}-${{ github.sha
        }}-aarch64-unknown-linux-gnu
      cancel-in-progress: false

    name: Pulumi

    permissions:
      contents: read
      id-token: write
      pull-requests: write

    runs-on: ubuntu-24.04

    env:
      AWS_REGION: eu-west-2
      ROLE_PULL_REQUEST: arn:aws:iam::588722779806:role/oidcPullRequestRole-f06bda4
      ROLE_PUSH: arn:aws:iam::588722779806:role/oidcPushRole-3ed1aa1
      STATE_BUCKET: pulumi-state-588722779806

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          audience: lambda-rssfilter-core-prod
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume:
            ${{ github.event_name == 'push' && env.ROLE_PUSH ||
            env.ROLE_PULL_REQUEST }}

      - name: Print session info
        run: aws sts get-caller-identity

      - name: Check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Build
        uses: ./.github/actions/build
        with:
          build-type:
            ${{ github.event_name == 'pull_request' && 'debug' || 'release' }}
          pkg-config-sysroot: /usr/lib/aarch64-linux-gnu
          target: aarch64-unknown-linux-gnu

      - name: Enable corepack
        run: |
          corepack enable

      - name: Set up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          cache-dependency-path: "pulumi/yarn.lock"
          node-version-file: "pulumi/package.json"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable
        working-directory: pulumi

      - name: Run pulumi
        uses: pulumi/actions@760956aff50b515c197ee22d30aa8d756f7b86a2 # v5.3.2
        env:
          PKG_CONFIG_SYSROOT_DIR: /usr/lib/aarch64-linux-gnu
        with:
          cloud-url:
            s3://${{ env.STATE_BUCKET }}?region=${{ env.AWS_REGION }}&awssdk=v2
          stack-name: organization/lambda-rssfilter/prod
          command: >-
            ${{
              (github.event_name == 'push' && github.ref == 'refs/heads/main')
              && 'up'
              || 'preview'
            }}
          comment-on-pr: true
          comment-on-summary: true
          work-dir: pulumi
