name: Renovate
on:
  schedule:
    # Offset by 12 minutes to avoid busy times on the hour
    - cron: 12 */4 * * *

  pull_request:
    paths:
      - .github/renovate-config.json5
      - .github/workflows/renovate.yml

  push:
    branches:
      - main
    paths:
      - .github/renovate-config.json5
      - .github/workflows/renovate.yml

  workflow_dispatch:
    inputs:
      dry-run:
        description: "Run Renovate in dry-run mode"
        required: false
        default: false
        type: boolean

      debug:
        description: "Run Renovate in debug mode"
        required: false
        default: false
        type: boolean

jobs:
  renovate:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          sparse-checkout: .github/renovate-config.json5

      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ secrets.LANEYBOT_APP_ID }}
          private-key: ${{ secrets.LANEYBOT_PRIVATE_KEY }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@68a3ea99af6ad249940b5a9fdf44fc6d7f14378b # v46.1.6
        with:
          configurationFile: .github/renovate-config.json5
          # renovate: datasource=docker depName=ghcr.io/renovatebot/renovate
          renovate-version: 43.86.0@sha256:a09b54d017aa7bd24b61a6d79f78fac6ebc651fb6c0cabaedd22915690c854c6
          token: ${{ steps.generate-token.outputs.token }}
        env:
          LOG_LEVEL:
            ${{ ((github.event_name == 'workflow_dispatch' && inputs.debug) ||
            (github.event_name == 'pull_request')) && 'debug' || 'info' }}
          # For pull requests, this means we'll get the dependencies of the PR's
          # branch, so you can fix/change things and see the results in the PR's
          # run. By default, Renovate will clone the main/default branch.
          RENOVATE_BASE_BRANCHES:
            ${{ github.event_name == 'pull_request' &&
            github.event.pull_request.head.ref || null }}
          # Dry run if the event is pull_request, or workflow_dispatch AND the dry-run input is true
          RENOVATE_DRY_RUN:
            ${{ (github.event_name == 'pull_request' || (github.event_name ==
            'workflow_dispatch' && github.event.inputs.dry-run == 'true')) &&
            'full' || null }}
          RENOVATE_PLATFORM: github
          RENOVATE_REPOSITORIES: ${{ github.repository }}
